'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,CheckCircle} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
export default function Contact(){const [topic,setTopic]=useState('Nytt bad'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(''),[design,setDesign]=useState('');useEffect(()=>{const p=new URLSearchParams(location.search);if(p.has('design'))setDesign(p.get('design')!.slice(0,1000));},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!consent)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email'),phone:f.get('phone'),message:f.get('message'),website:f.get('website'),topic,consent,design})});const d=await r.json() as {error?:string;id:string};if(!r.ok)throw Error(d.error||'Kunne ikke lagre henvendelsen.');setReceipt(d.id);}catch(e){setError((e as Error).message+' Prøv igjen eller ring 76 94 59 70.');}finally{setBusy(false)}}
if(receipt)return <div className="form-success" role="status"><CheckCircle size={42}/><h2>Takk for henvendelsen!</h2><p>Meldingen er lagret i nettstedets innboks. Referanse: <strong>{receipt.slice(0,8)}</strong>.</p><p>Dette er ikke en bekreftet avtale. Haster det, ring oss på <a href="tel:+4776945970">76 94 59 70</a>.</p><button className="btn navy" onClick={()=>{setReceipt('');setConsent(false)}}>Send en ny henvendelse</button></div>;
return <form className="contact-form" onSubmit={submit}><span className="eyebrow">FORTELL OSS OM PROSJEKTET</span><h2>Hvordan kan vi hjelpe?</h2><div className="form-row"><label>Navn<input name="name" required minLength={2} maxLength={120} autoComplete="name" placeholder="Ditt navn"/></label><label>Telefon<input name="phone" type="tel" maxLength={30} autoComplete="tel" placeholder="Telefonnummer"/></label></div><label>E-post<input name="email" type="email" required maxLength={200} autoComplete="email" placeholder="deg@eksempel.no"/></label><label>Hva gjelder det?</label><Select value={topic} onValueChange={setTopic}><SelectTrigger className="form-select" aria-label="Hva gjelder henvendelsen?"><SelectValue/></SelectTrigger><SelectContent>{['Nytt bad','Rørleggerarbeid','Befaring og planlegging','Butikk og produkter','Annet'].map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><label>Melding<textarea name="message" required minLength={10} maxLength={4000} rows={5} placeholder="Fortell litt om hva du ønsker hjelp med, hvor og når …"/></label>{design&&<div className="design-attached"><strong>Valg fra showroom er vedlagt</strong><p>{design}</p><button type="button" onClick={()=>setDesign('')}>Fjern vedlegg</button></div>}<label className="honeypot" aria-hidden="true">La dette feltet stå tomt<input name="website" tabIndex={-1} autoComplete="off"/></label><div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">Jeg har lest <a href="/personvern">personvernerklæringen</a> og godtar at opplysningene brukes til å følge opp henvendelsen.</label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="btn navy" disabled={busy||!consent}>{busy?'Sender …':'Send henvendelse'}<ArrowUpRight size={18}/></button><small>Henvendelsen lagres i nettstedets innboks. Unngå sensitive opplysninger.</small></form>}
