'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState,useEffect,useRef} from 'react';
import {Menu,X,ArrowUpRight,Phone,MessageCircle,Send,Plus,Minus} from 'lucide-react';
import {navigation} from '@/lib/content';
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();useEffect(()=>setOpen(false),[path]);return <><div className="topline"><span>Din lokale rørlegger i Narvik · Siden 1983</span><a href="tel:+4776945970"><Phone size={13}/> 76 94 59 70</a></div><header className="header"><Link href="/" className="brand" aria-label="Ofoten Rør forside"><img src="/logo.svg" alt="Ofoten Rør" className="brand-logo"/></Link><nav className={open?'nav open':'nav'} aria-label="Hovedmeny">{navigation.slice(1).map(([url,label])=><Link key={url} href={url} className={path===url?'active':''}>{label}</Link>)}</nav><button className="menu" aria-label={open?'Lukk meny':'Åpne meny'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></>}
export function Footer(){return <footer><div className="footer-grid"><div><Link href="/" className="footer-brand">OFOTEN RØR<span>Et godt bad begynner<br/>med en god samtale.</span></Link><a href="tel:+4776945970" className="footer-phone">76 94 59 70 <ArrowUpRight/></a></div><div><h3>Kom innom</h3><p>Dronningensgate 18<br/>8514 Narvik</p><p>Man–fre 08–16<br/>Lørdag 10–14</p><small>Gratis kundeparkering</small></div><div><h3>Utforsk</h3>{[['/tjenester','Tjenester'],['/showroom','3D-showroom'],['/ansatte','Våre ansatte'],['/historie','Vår historie'],['/kontakt','Kontakt oss']].map(([u,t])=><Link key={u} href={u}>{t}</Link>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ofoten Rør</span><Link href="/personvern">Personvern</Link><Link href="/innboks">Ansattinnboks</Link></div></footer>}
type Msg={role:'user'|'assistant';content:string};
export function Chat(){const [open,setOpen]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState(''),[messages,setMessages]=useState<Msg[]>([{role:'assistant',content:'Hei! Hva lurer du på om Ofoten Rør eller ditt nye bad?'}]);const end=useRef<HTMLDivElement>(null);useEffect(()=>{if(open)end.current?.scrollIntoView({block:'nearest'});},[messages,busy,open]);useEffect(()=>{fetch('/api/chat').then(r=>r.json()).then(d=>setMode((d as {mode:string}).mode)).catch(()=>setMode('unavailable'));},[]);
async function send(text:string){if(!text.trim()||busy)return;const next=[...messages,{role:'user' as const,content:text.trim()}];setMessages(next);setInput('');setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next.slice(-12)})});const data=await r.json() as {error?:string;mode:string;answer:string};if(!r.ok)throw Error(data.error||'Chatten er utilgjengelig. Prøv igjen.');setMode(data.mode);setMessages([...next,{role:'assistant',content:data.answer}]);}catch(e){setMessages([...next,{role:'assistant',content:(e as Error).message+' Du kan også ringe 76 94 59 70.'}]);}finally{setBusy(false)}}
return <div className="chat"><button className="chat-launch" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="chat-panel">{open?<X size={22}/>:<MessageCircle size={22}/>}<span>{open?'Lukk':'Spør oss'}</span></button>{open&&<section id="chat-panel" className="chat-panel" aria-label="Chat med Ofoten Rør"><div className="chat-head"><MessageCircle/><div><strong>Ofoten-assistenten</strong><small>{mode==='ai'?'AI-assistent':'Svar fra bedriftens informasjon'}</small></div><button onClick={()=>setOpen(false)} aria-label="Lukk chat"><X size={20}/></button></div>{mode!=='ai'&&<p className="chat-notice">AI er ikke tilkoblet ennå. Her får du automatiske svar på vanlige spørsmål.</p>}<div className="chat-messages" role="log" aria-live="polite">{messages.map((m,i)=><p key={i} className={'message '+m.role}>{m.content}</p>)}{busy&&<p className="message assistant">Henter svar …</p>}<div ref={end}/></div><div className="suggestions">{['Åpningstider','Planlegge nytt bad','Befaring'].map(t=><button key={t} disabled={busy} onClick={()=>send(t)}>{t}</button>)}</div><form onSubmit={e=>{e.preventDefault();send(input)}}><input aria-label="Ditt spørsmål" value={input} onChange={e=>setInput(e.target.value)} placeholder="Skriv et spørsmål …" maxLength={1500}/><button disabled={busy||!input.trim()} aria-label="Send spørsmål"><Send size={19}/></button></form><small className="chat-privacy">Ikke del sensitive opplysninger. <Link href="/personvern">Personvern</Link></small></section>}</div>}
export function FAQ(){const [active,setActive]=useState(-1);return <div className="faq">{[['Kan dere ta hele oppussingen av badet?','Ja. Ofoten Rør tilbyr totalrenovering og har rørlegger, snekker, fliselegger og elektriker tilgjengelig. Vi avklarer hva prosjektet ditt trenger.'],['Kan jeg se badet i 3D først?','Ja, vi tilbyr tegning og planlegging i 3D. Du kan også prøve materialer og løsninger i vårt interaktive showroom her på nettsiden.'],['Hvor finner jeg butikken?','I Dronningensgate 18 i Narvik. Vi har omtrent 300 m² med fagbutikk og utstillinger, og gratis parkering for kunder.'],['Hva koster et nytt bad?','Prisen avhenger av størrelse, tilstand, materialer og omfang. Kontakt oss for befaring og et konkret tilbud.']].map(([q,a],i)=><div key={q}><button aria-expanded={i===active} aria-controls={'faq-'+i} onClick={()=>setActive(i===active?-1:i)}>{q}{i===active?<Minus size={18}/>:<Plus size={18}/>}</button>{i===active&&<p id={'faq-'+i}>{a}</p>}</div>)}</div>}
