import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowUpRight,MapPin,Phone,Clock,Mail} from 'lucide-react';
import {photos,employees,imageBase,services} from '@/lib/content';
import Contact from '../components/contact';
import Gallery from '../components/gallery';
import Showroom from '../components/showroom';
const titles:Record<string,string>={'tjenester':'Fagfolk for hele badet.','om-oss':'Godt håndverk. Gode folk.','historie':'En del av Narvik siden 1983.','ansatte':'Menneskene bak håndverket.','galleri':'Finn ditt neste uttrykk.','prosjekter':'Fra første idé til ferdig rom.','kontakt':'La oss ta en prat.','showroom':'Ditt bad. Dine muligheter.','personvern':'Personvern'};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:titles[slug]||'Side ikke funnet'}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(!titles[slug])notFound();return <><section className={'page-heading '+(slug==='showroom'?'compact':'')}><div className="breadcrumbs"><Link href="/">Forside</Link><span>/</span><span>{slug==='om-oss'?'Om oss':slug==='showroom'?'3D-showroom':slug.charAt(0).toUpperCase()+slug.slice(1)}</span></div><span className="eyebrow">OFOTEN RØR</span><h1>{titles[slug]}</h1>{slug==='showroom'?<p>Gå inn, se deg rundt og prøv materialer i et digitalt inspirasjonsbad.</p>:slug==='galleri'?<p>Ekte bilder fra Ofoten Rørs butikk, folk og baderomsutstillinger.</p>:null}</section>
{slug==='showroom'&&<Showroom/>}
{slug==='galleri'&&<section className="section page-body"><Gallery/></section>}
{slug==='tjenester'&&<section className="section page-body"><div className="service-details">{services.map((s,i)=><article id={'tjeneste-'+i} key={s.title}><span className="service-number">0{i+1}</span><div><span className="eyebrow">{s.tag}</span><h2>{s.title}</h2><p>{s.text}</p><p>{['Vi starter med en samtale om behov, ønsker og rammene for oppussingen. Deretter planlegger vi løsningen og samordner fagene som trengs.','Ta kontakt om montering, utskifting eller arbeid på badet. Vi avklarer hva som må undersøkes på stedet før vi kan gi et konkret tilbud.','En tegning gjør det lettere å vurdere planløsning og plass. Ta gjerne med mål eller bilder. Vi kan også komme hjem til deg for å hjelpe med planleggingen.','I utstillingene kan du sammenligne uttrykk og se løsninger på nært hold. Besøk oss i Dronningensgate 18, og få hjelp av folk som kjenner produktene.'][i]}</p><Link className="text-link" href="/kontakt">Snakk med oss <ArrowUpRight size={18}/></Link></div><img src={i%2===0?photos.hero:photos.detail} alt="Baderomsinspirasjon hos Ofoten Rør" loading="lazy"/></article>)}</div></section>}
{slug==='om-oss'&&<><section className="section split about-page"><img src={photos.team} alt="Ofoten Rørs medarbeidere"/><div><span className="eyebrow">LOKAL FAGBUTIKK OG RØRLEGGER</span><h2>Vi hjelper deg med å se mulighetene.</h2><p>Ofoten Rør har røtter i Narvik helt tilbake til 1983. Vi kombinerer praktisk håndverk med hjelp til å velge løsningene som fungerer i ditt hjem.</p><p>Hos oss kan du planlegge et nytt bad, se innredning i butikken og få hjelp med gjennomføringen. Vi har rørleggere og tilgang til de øvrige fagene som trengs ved totalrenovering.</p><div className="actions"><Link className="btn navy" href="/ansatte">Møt våre ansatte <ArrowUpRight size={18}/></Link><Link className="text-link" href="/historie">Vår historie</Link></div></div></section><section className="section store-section"><span className="eyebrow">VELKOMMEN INNOM</span><h2>En butikk full av muligheter.</h2><p>Omtrent 300 m² med fagbutikk og utstillinger. Gratis kundeparkering. Og tid til en god samtale om badet ditt.</p><img src={photos.showroom} alt="Baderomsutstillinger inne i Ofoten Rørs butikk" loading="lazy"/></section></>}
{slug==='historie'&&<section className="section history"><img src={photos.store} alt="Ofoten Rør i Narvik"/><div className="timeline">{[['1983','Her begynner historien','Ofoten Rør etableres. Dette er starten på bedriftens historie som lokal rørlegger og fagbutikk i Narvik.'],['2018','Nytt liv i butikken','Høsten 2018 moderniseres butikken med nye gulv, himlinger, belysning og baderomsutstillinger.'],['I dag','Håndverk og muligheter','Fra Dronningensgate 18 hjelper vi kunder med baderom, planlegging og rørleggerarbeid. 3D-tegning gjør det enklere å se løsningen før arbeidet starter.']].map(([year,title,text])=><article key={year}><span>{year}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div></section>}
{slug==='ansatte'&&<section className="section page-body"><p className="intro">Møt teamet vårt. Ta gjerne direkte kontakt med en av våre kontaktpersoner, eller ring butikken på 76 94 59 70.</p><div className="employees">{employees.map(([name,role,img,phone,email])=><article key={name}><img src={imageBase+img} alt={name} loading="lazy"/><h2>{name}</h2><p>{role}</p>{phone&&<a href={'tel:+47'+phone}><Phone size={15}/>{phone.replace(/(\d{3})(\d{2})(\d{3})/,'$1 $2 $3')}</a>}{email&&<a href={'mailto:'+email}><Mail size={15}/> {email}</a>}</article>)}</div></section>}
{slug==='prosjekter'&&<section className="section page-body"><div className="split"><img src={photos.hero} alt="Baderomsutstillinger fra Ofoten Rør"/><div><span className="eyebrow">DITT NESTE PROSJEKT</span><h2>Gode valg fra starten.</h2><p>Et nytt bad begynner med dine behov. Vi hjelper med planlegging, visualisering og samordning av håndverksfagene.</p><p>Bildene viser inspirasjon og utstillinger fra vår egen nettside. Ønsker du referanser fra gjennomførte kundeprosjekter, ta kontakt – så kan vi vise relevante eksempler.</p><Link className="btn navy" href="/kontakt">Snakk med oss om ditt prosjekt <ArrowUpRight size={18}/></Link></div></div><div className="process">{[['01','Samtalen','Vi blir kjent med ønskene dine og hva du ønsker å endre.'],['02','Planen','Vi ser på rommet, tegner løsningen og avklarer materialer og omfang.'],['03','Gjennomføringen','Rørlegger, snekker, fliselegger og elektriker samordnes etter behov.'],['04','Detaljene','Vi går gjennom resultatet og avklarer videre bruk og oppfølging.']].map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>}
{slug==='kontakt'&&<section className="section contact-layout"><div className="contact-info"><h2>Kom innom.<br/>Eller ta kontakt.</h2><div><Phone/><p><strong>Ring oss</strong><a href="tel:+4776945970">76 94 59 70</a></p></div><div><Mail/><p><strong>Planlegging og befaring</strong><a href="mailto:rune@ofotenror.no">rune@ofotenror.no</a></p></div><div><MapPin/><p><strong>Besøk butikken</strong>Dronningensgate 18<br/>8514 Narvik<br/><a href="https://www.google.com/maps/search/?api=1&query=Ofoten+R%C3%B8r+Dronningensgate+18+Narvik" target="_blank" rel="noreferrer">Se veibeskrivelse ↗</a></p></div><div><Clock/><p><strong>Åpningstider</strong>Mandag–fredag: 08–16<br/>Lørdag: 10–14<br/>Søndag: stengt</p></div><img src={photos.store} alt="Butikken til Ofoten Rør"/></div><Contact/></section>}
{slug==='personvern'&&<section className="section legal"><h2>Kontaktopplysninger</h2><p>Ofoten Rør, Dronningensgate 18, 8514 Narvik. Spørsmål om opplysninger du har sendt inn kan rettes til rune@ofotenror.no eller telefon 76 94 59 70.</p><h2>Kontaktskjema</h2><p>Når du sender skjemaet, lagres navn, e-post, telefon, melding og eventuelle showroomvalg i nettstedets beskyttede innboks. Opplysningene brukes til å følge opp henvendelsen din. Tilgangen er begrenset til nettstedets administrator. Du kan be om innsyn, retting eller sletting ved å kontakte oss. Henvendelser bør slettes når de ikke lenger er nødvendige for oppfølgingen.</p><h2>Chat</h2><p>Chatten viser om den bruker AI eller forhåndsskrevne svar. Når AI er aktiv, sendes de siste meldingene til OpenAI for å lage et svar. Samtalen lagres ikke i nettstedets database. Ikke skriv fødselsnummer, helseopplysninger, passord eller annen sensitiv informasjon.</p><h2>3D-showroom og teknisk drift</h2><p>Showroomet er en illustrasjon, ikke et bindende tilbud. Designvalg lagres i lenken når du deler et design. Nettstedet bruker ikke egne analyse- eller reklamesporingsverktøy. Plattformen kan bruke nødvendige funksjoner for drift og innlogging. Eksterne kart åpnes først når du klikker på kartlenken.</p></section>}
</>}
